version: '3.4'

services:
  pricelists.webapp:
    image: ${DOCKER_REGISTRY-}pricelistswebapp
    build:
      context: .
      dockerfile: PriceLists.WebApp/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'MyStrongPassword1!'
    ports:
      - "1433:1433"
    volumes:
      - pricelistsdb-volume:/var/lib/mssql/data
volumes:
  pricelistsdb-volume:
